### ISSUE TITLE
Configuration file for TMT250

### ISSUE THREAD

**Issue by rphlo** [klemenkenda/o-gpsy#6]
Could you share the teltonika configuration file you use for the TMT250 for a typical streaming session?

**Comment by klemenkenda** [comment]
So far I did not experiment with this much; I've only set up server information (for TCP) and update interval, which is 1 second. I plan to check, how GPSseuranta configures the device and add configuration. However, this will not be done shortly. Did you manage to start the system?

**Comment by rphlo** [comment]
I was just curious to see if you had come up with a default setup for the tmt250 device, I am working on a similar project in Python and just added support for this device. I figured out a configuration that seemed to work. TCP, 1sec GPS interval if movement..., 15sec interval for GPRS send...

**Comment by klemenkenda** [comment]
Nice. :) Could you then share your config? :)

**Comment by rphlo** [comment]
You can download it here https://www.routechoices.com/static/tmt250.cfg
